### ISSUE TITLE
Maret: dev

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/dm_apps#1064]
### Action:
Fix and respond to tickets requested by Kaitlin via DMapps

### Context:
There are a lot of small tickets that can be grouped together in this single issue to reduce reporting effort a bit.

### Tasks (Effort):

- [x] Fix New Org 500 error (1)
- [x] Organization "Last modified by" (3)
- [x] Editing organization member - last modified (0, same fix as ticket above)
- [x] Date of interaction header (1)
- [x] Search function - interactions (1)
- [x] Search on committees / working groups page (1)
- [x] Numbered interactions on committee pages (1)
Total: 8
